#version 330 core

in vec3 v_WorldNormal;
in vec3 v_WorldPos;
in vec2 v_TexCoord;
in vec3 v_Color;
in float v_EdgeDist;

uniform sampler2D u_Texture;
uniform int       u_Textured;     // 1 = pixel-art texture, 0 = solid colour tile
uniform int       u_TintMode;     // 0 = normal alpha-blend, 1 = multiplicative tint (use with neutral greyscale tiles)
uniform int       u_SoftEdge;     // 1 = soft-edge blend pass: output feathered alpha so variants fade into each other
uniform vec3      u_SunDir;
uniform vec3      u_SunColor;
uniform vec3      u_AmbientColor;
uniform float     u_FogDensity;
uniform vec3      u_FogColor;
uniform vec3      u_CameraPos;

out vec4 FragColor;

void main() {
    vec4 texSample = texture(u_Texture, v_TexCoord);
    vec3 texColor  = texSample.rgb;
    vec3 color;

    // ── Soft-edge blend pass ──────────────────────────────────────────────────
    // Drawn on top of the solid base pass with GL_BLEND enabled.
    // Texture fades to transparent near the hex edge so adjacent variants
    // transition through the shared dither base rather than hard-cutting.
    if (u_SoftEdge != 0 && u_Textured != 0) {
        float softAlpha = (1.0 - smoothstep(0.40, 0.49, v_EdgeDist)) * texSample.a;
        FragColor = vec4(texColor, softAlpha);
        return;
    }

    if (u_Textured != 0) {
        // ── Pixel-art terrain tile ────────────────────────────────────────────
        if (u_TintMode != 0) {
            // Multiplicative tint: greyscale/neutral tile gets recoloured by
            // the terrain base colour.  Multiply-2x preserves luminance at mid-grey.
            // Use with _neutral.png variants generated by scripts/fix_hex_fill.py.
            color = clamp(texColor * v_Color * 2.0, 0.0, 1.0);
            // Transparent pixels (outside hex in tile image) fall back to base colour.
            color = mix(v_Color, color, texSample.a);
        } else {
            // Alpha-blend texture over the solid base terrain colour.
            // Transparent areas show base terrain colour; opaque areas show texture as-is.
            color = mix(v_Color, texColor, texSample.a);
        }

        // Very faint hex-edge darkening — just enough to read tile boundaries
        // without overwriting the pixel art edge detail.
        float edgeFactor = smoothstep(0.44, 0.50, v_EdgeDist);
        color = mix(color, color * 0.70, edgeFactor * 0.30);

    } else {
        // ── Ordered-dither terrain (LucasArts VGA style) ──────────────────────
        // Two palette entries: shadow and highlight from base terrain colour.
        vec3 colDark  = v_Color * 0.65;
        vec3 colLight = min(v_Color * 1.35, vec3(1.0));

        // Two-scale Bayer dither: fine grain (4 px) + coarse (8 px).
        // Mixing scales breaks the uniform grid and gives a painted feel.
        const int b[16] = int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
        ivec2 sc      = ivec2(gl_FragCoord.xy);
        float bFine   = float(b[(sc.x & 3)        | ((sc.y & 3) << 2)])        / 16.0;
        float bCoarse = float(b[((sc.x >> 1) & 3) | (((sc.y >> 1) & 3) << 2)]) / 16.0;
        float bayer   = bFine * 0.65 + bCoarse * 0.35;

        // Hex-local radial gradient: lighter centre, darker rim.
        float hexLight = clamp(1.0 - v_EdgeDist * 2.2 + 0.15, 0.0, 1.0);

        // World-space sine variation: slow organic brightness shift between hexes
        // (~3-hex period) so adjacent tiles feel hand-painted, not stamped.
        float worldVar = sin(v_WorldPos.x * 1.8 + 0.7) * cos(v_WorldPos.z * 2.1 + 1.3)
                         * 0.5 + 0.5;

        // Blend: structural (hex gradient) + fine grain (bayer) + slow variation.
        float blend = hexLight * 0.55 + bayer * 0.30 + worldVar * 0.15;
        color = (blend >= 0.5) ? colLight : colDark;

        // Crisp tile-boundary darkening reads as grid lines.
        float edgeFactor = smoothstep(0.40, 0.50, v_EdgeDist);
        color = mix(color, color * 0.58, edgeFactor * 0.45);
    }

    // Distance fog
    float dist      = length(v_WorldPos - u_CameraPos);
    float fogFactor = clamp(1.0 - exp(-u_FogDensity * dist), 0.0, 0.6);
    color = mix(color, u_FogColor, fogFactor);

    FragColor = vec4(color, 1.0);
}
